name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Every hour, or adjust as needed
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the fork
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/alikatteRajakala/github-actions-python-example.git
        git fetch upstream
        git checkout main
        git merge upstream/main
        git push origin main
